version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - sparknamenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    ports:
      - 50070:50070
    networks:
      - spark-net
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - sparkdatanode:/hadoop/dfs/data
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      SERVICE_PRECONDITION: "namenode:50070"
    networks:
      - spark-net
  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.8-hive-java8
    ports:
      - 8081:8080
      - 7077:7077
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    networks:
      - spark-net
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.8-hive-java8
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      SERVICE_PRECONDITION: "spark-master:8080"
    networks:
      - spark-net

volumes:
  sparknamenode:
  sparkdatanode:

networks:
  spark-net:
    external:
      name: spark-net
